name: security_on_pr

on: [pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
